[package]
name = "rgpt-cfg"
version = "0.1.0"
edition.workspace = true

[dependencies]
rgpt-db.workspace = true
rgpt-stream.workspace = true

async-openai.workspace = true
tokio.workspace = true
reqwest.workspace = true
