[package]
name = "retro_gpt_backend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "retro_gpt_backend"
path = "backend/main.rs"

[lib]
name = "retro_gpt_backend"
path = "backend/lib.rs"

[dependencies]
serde_json = "1.0.133"
tiny_http = "0.12.0"
url = "2.5.4"
urlencoding = "2.1.3"
