[workspace]
resolver = "2"
members = [
    "crates/librgpt",
    "crates/rgpt"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
librgpt = { path = "crates/librgpt" }
