services:
  app:
    profiles:
    - dev
    - prod
    container_name:
      app
    build:
      context: .
      target: app
    env_file:
      - ./.env

  nginx-dev:
    profiles:
      - dev
    image:
      nginx:latest
    container_name:
      nginx-dev
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - app


  nginx-prod:
    profiles:
      - prod
    image:
      nginx:latest
    container_name:
      nginx-prod
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

