services:
  app:
    container_name:
      app
    build:
      context: .
      target: app
    env_file:
      - ./.env

  nginx:
    image:
      nginx:latest
    container_name:
      nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
