services:
  rgpt_api:
    profiles:
      - dev
      - prod
    container_name: rgpt_api
    build:
      context: .
      target: api
    env_file:
      - .env
      - .pub.env
    depends_on:
      - db
    ports:
      - 4002:4002

  rgpt_static:
    profiles:
      - dev
      - prod
    container_name: rgpt_static
    build:
      context: .
      target: static
    env_file:
      - .env
      - .pub.env
    depends_on:
      - db

  db:
    profiles:
      - dev
      - prod
    container_name: db
    image: postgres:latest
    restart: always
    env_file:
      - .env
      - .pub.env
    ports:
      - 3003:5432
    volumes:
      - rgpt_postgres:/var/lib/postgresql/data

  nginx-dev:
    profiles:
      - dev
    image: nginx:latest
    container_name: nginx-dev
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - rgpt_api
      - rgpt_static
    env_file:
      - .env
      - .pub.env

  nginx-prod:
    profiles:
      - prod
    image: nginx:latest
    container_name: nginx-prod
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.template:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - rgpt_api
      - rgpt_static
    env_file:
      - .env
      - .pub.env
    command: /bin/bash -c "export DOLLAR="$" && envsubst < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

volumes:
  rgpt_postgres:
