[server]
port = 3000

[statics]
[[statics.file]]
url_path = "/"
local_path = "static/index.html"
mime_type = "text/html"

[[statics.file]]
url_path = "/chatlogo.png"
local_path = "static/chatlogo.png"
mime_type = "image/png"

[[statics.file]]
url_path = "/secondclip.mp4"
local_path = "static/tmp_secondclip.mp4"
mime_type = "video/mp4"

[[statics.file]]
url_path = "/bw.mp4"
local_path = "static/bw.mp4"
mime_type = "video/mp4"
