[package]
name = "regto-gpt-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
reqwest = { version = "0.12.9", features = ["blocking"] }
thiserror = "2.0.6"
tiny_http = "0.12.0"
