[package]
name = "libserver"
version = "0.1.0"
edition.workspace = true

[dependencies]
bytes.workspace = true
futures.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
tokio.workspace = true
tower.workspace = true
