[package]
name = "librgpt"
version = "0.1.0"
edition = "2021"

[dependencies]
rgpt-db.workspace = true
rgpt-server.workspace = true
rgpt-cfg.workspace = true
libserver.workspace = true

async-openai = "0.27.2"
tokio = { version = "1.42.0", features = ["full"] }
