[package]
name = "rgpt-db"
version.workspace = true
edition.workspace = true

[dependencies]
libserver.workspace = true

diesel.workspace = true
diesel-async.workspace = true
chrono.workspace = true
tokio.workspace = true
uuid.workspace = true
