name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Check out code
        uses: blacksmith-actions/checkout@v1

      - name: Set up Docker Buildx
        uses: blacksmith-actions/setup-buildx@v1

      - name: Build Docker image with cache
        uses: blacksmith-actions/build-push@v1
        with:
          context: .
          push: false
          tags: my-image:latest
          cache-from: type=blacksmith
          cache-to: type=blacksmith,mode=max
